[project]
name = "expds"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "pyyaml",
    "scipy>=1.17.1",
    "laspy>=2.7.0",
    "lazrs>=0.8.2",
    "rasterio>=1.4.4",
    "pyproj>=3.7.2",
]

[dependency-groups]
dev = ["pytest", "ruff", "pre-commit", "nbstripout"]

[tool.ruff]
line-length = 100
extend-exclude = ["notebooks"]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/expds"]
