[project]
name = "expds"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "pyyaml",
    "scipy>=1.17.1",
    "laspy>=2.7.0",
    "lazrs>=0.8.2",
    "rasterio>=1.4.4",
    "pyproj>=3.7.2",
    "torch>=2.14.0",
    "segmentation-models-pytorch>=0.5.0",
    "scikit-image>=0.26.0",
    "django>=5.1",
    "djangorestframework",
    "django-environ",
]

[dependency-groups]
dev = ["pytest", "ruff", "pre-commit", "nbstripout", "pytest-django", "django-debug-toolbar"]

[tool.ruff]
line-length = 100
extend-exclude = ["notebooks", "web/static", "web/media", "web/**/migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.pytest.ini_options]
testpaths = ["tests"]
DJANGO_SETTINGS_MODULE = "web.config.settings"
python_files = ["test_*.py", "*_test.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/expds"]
